### ISSUE TITLE
Incomplete es2015 preset

### ISSUE THREAD

**Issue by wyuenho** [cloudflare/babel-preset-cf#1]
Are there any specific reason we are missing a couple of transforms from the babel es2015 preset?

[Ours](https://github.com/cloudflare/babel-preset-cf/blob/master/index.js)
[Babel's](https://github.com/babel/babel/blob/master/packages/babel-preset-es2015/index.js)

**Comment by jamiebuilds** [comment]
Yes I've omitted things that have complicated transforms that makes the generated code difficult to debug.
